

<br>
<br>
<br>



```{r '{{typ_szk}},D2setup', echo=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, results='asis', 
 fig.width = 10, fig.height = 10, fig.path = "figPOL/", 
 out.width = "100%")
typ_szk <-  "{{typ_szk}}"
ewaluowana_edycja <- {{edycja}}
ewaluowany_rok_abs <- {{rok_abs}}

set_flextable_defaults(
#  font.family = "Cambria",
  font.size = 10,
  padding = 2,
  border.color = "#CCCCCC",
  line_spacing = 1.08,
  digits = 2,
  decimal.mark = ",",
  big.mark = " ",
  na_str = "<na>"
)

```


```{r '{{typ_szk}},d2w1', fig.height=4, fig.width=10}
if (typ_szk %in% "Szkoła policealna") {
    cat0("## Uzyskiwanie świadectwa dojrzałości - absolwenci ",  dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. {-} \n\n",
    
        "Absolwenci ", dopelniacz(typ_szk)," nie mogą zdobywać tego typu dyplomów.")
}
if (typ_szk %in% szkoly_branzowe) {
    cat0("### Uzyskiwanie świadectwa dojrzałości - absolwenci ",  dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. {-} \n\n",
    
        "Absolwenci ", dopelniacz(typ_szk)," nie mogą zdobywać tego typu dyplomów.")
}

if (typ_szk %in% szkoly_maturalne) {
  
  cat0("## Uzyskiwanie świadectwa dojrzałości - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. {-} \n\n")
}

if (tylko_tabele == FALSE &&
    typ_szk %in% szkoly_maturalne) {
  cat0("Wykres ", wyk_num(), ": Uzyskiwanie świadectwa dojrzałości - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. - ogółem i w podziale na płeć\n\n")


(wykresMaturyPlec %+% 
    dane_wyk_D2_plec(pelna_finalna_ramka_wskaznikow, 
                     typ_szk, ewaluowany_rok_abs)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 16) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(ewaluowana_edycja)
}
```

```{r '{{typ_szk}},d2t1'}
if (typ_szk %in% szkoly_maturalne)  {
cat0("Tabela ", tab_num(), ": Uzyskiwanie świadectwa dojrzałości - absolwenci ", dopelniacz(typ_szk), " z ", ewaluowany_rok_abs, " r. - ogółem i w podziale na płeć\n\n")
  
dane_tab_D2_plec(pelna_finalna_ramka_wskaznikow, 
                 typ_szk, ewaluowany_rok_abs) %>% 
  gentab_tab_D(ewaluowana_edycja)
}
```

```{r '{{typ_szk}},d2w2'}
if (tylko_tabele == FALSE &&
    typ_szk %in% c("Technikum", "Branżowa szkoła II stopnia")) {
  cat0("Wykres ", wyk_num(), ": Uzyskiwanie świadectwa dojrzałości - absolwenci ", dopelniacz(typ_szk), " z ", ewaluowany_rok_abs, " r. - w podziale na zawody o największej liczbie absolwentów\n\n")


(wykresMaturyZawod %+% 
    dane_wyk_D2_zaw(pelna_finalna_ramka_wskaznikow, 
                    typ_szk, ewaluowany_rok_abs)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 14) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(ewaluowana_edycja)
}
```

```{r '{{typ_szk}},d2t2'}
if (typ_szk %in% c("Technikum", "Branżowa szkoła II stopnia")) {
  cat0("Tabela ", tab_num(), ": Uzyskiwanie świadectwa dojrzałości - absolwenci ", dopelniacz(typ_szk), " z ", ewaluowany_rok_abs, " r. - w podziale na zawody o największej liczbie absolwentów\n\n")
  
dane_tab_D2_zaw(pelna_finalna_ramka_wskaznikow, 
                 typ_szk, ewaluowany_rok_abs, tylko_tabele) %>% 
  gentab_tab_D(ewaluowana_edycja)
}
```

