

<br>
<br>
<br>



```{r '{{typ_szk}},W1setup', echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, results='asis', 
                      fig.width = 10, fig.height = 10, fig.path = "figPOL/", 
                      out.width = "100%")
typ_szk <-  "{{typ_szk}}"
ewaluowana_edycja <- {{edycja}}
ewaluowany_rok_abs <- {{rok_abs}}
ewaluowany_rok <- {{rok}}
if ({{edycja}} == {{rok_abs}} + 2) {
  ewaluowany_kolejny_rok = {{rok_abs}} + 1
}

set_flextable_defaults(
#  font.family = "Cambria",
  font.size = 10,
  padding = 2,
  border.color = "#CCCCCC",
  line_spacing = 1.08,
  digits = 2,
  decimal.mark = ",",
  big.mark = " ",
  na_str = "<na>"
)
```


```{r '{{typ_szk}},W1t1'}
if (typ_szk %in% szkoly_branzowe) {
cat0("### Przychody - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. {-}\n\n")
}
if (typ_szk %ni% szkoly_branzowe) {
cat0("## Przychody - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. {-}\n\n")
}

if (typ_szk %ni% "Szkoła specjalna przysposabiająca do pracy") {
cat0("Tabela ", tab_num(), ": Średnie miesięczne przychody w czwartym kwartale ", ewaluowany_rok," r. - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. - w podziale na płeć\n\n")
  
dane_tab_W1(pelna_finalna_ramka_wskaznikow, 
            typ_szk, "sexf", ewaluowany_rok_abs, 
            ewaluowany_rok, tylko_tabele) %>%
  gentab_tab_D(ewaluowana_edycja)
}

```

```{r '{{typ_szk}},W1t2'}
if (typ_szk %in% szkoly_z_zawodem) {
cat0("Tabela ", tab_num(), ": Średnie miesięczne przychody w czwartym kwartale ", ewaluowany_rok," r. - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. - w podziale na zawody o największej liczbie absolwentów\n\n")
  
dane_tab_W1(pelna_finalna_ramka_wskaznikow, 
            typ_szk, "nazwa_zaw", ewaluowany_rok_abs, 
            ewaluowany_rok, tylko_tabele) %>%
  gentab_tab_D(ewaluowana_edycja)
}
```

```{r '{{typ_szk}},W1t3'}
if (ewaluowana_edycja == (ewaluowany_rok_abs + 2) &&
    typ_szk %ni% "Szkoła specjalna przysposabiająca do pracy") {
   cat0("Tabela ", tab_num(), ": Średnie miesięczne przychody w całym ", ewaluowany_kolejny_rok," r. - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. - ogółem i w podziale na płeć\n\n")
  
dane_tab_W1(pelna_finalna_ramka_wskaznikow, 
            typ_szk, "sexf", ewaluowany_rok_abs, 
            ewaluowany_kolejny_rok, tylko_tabele) %>%
  gentab_tab_D(ewaluowana_edycja)
}
```

```{r '{{typ_szk}},W1t4'}
if (ewaluowana_edycja == (ewaluowany_rok_abs + 2) &&
    typ_szk %in% szkoly_z_zawodem) {
cat0("Tabela ", tab_num(), ": Średnie miesięczne przychody w całym ", ewaluowany_kolejny_rok," r. - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. - w podziale na zawody o największej liczbie absolwentów\n\n")
  
dane_tab_W1(pelna_finalna_ramka_wskaznikow, 
            typ_szk, "nazwa_zaw", ewaluowany_rok_abs, 
            ewaluowany_kolejny_rok, tylko_tabele) %>%
  gentab_tab_D(ewaluowana_edycja)
}
```

```{r '{{typ_szk}},W1t5'}

   cat0("Tabela ", tab_num(), ": Średnie miesięczne przychody w pierwszym kwartale ", ewaluowana_edycja," r. - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. - ogółem i w podziale na płeć\n\n")
if (typ_szk %ni% "Szkoła specjalna przysposabiająca do pracy") {  
dane_tab_W1(pelna_finalna_ramka_wskaznikow, 
            typ_szk, "sexf", ewaluowany_rok_abs, 
            ewaluowana_edycja, tylko_tabele) %>%
  gentab_tab_D(ewaluowana_edycja)
}
```

```{r '{{typ_szk}},W1t6'}
if (typ_szk %in% szkoly_z_zawodem) {
cat0("Tabela ", tab_num(), ": Średnie miesięczne przychody w pierwszym kwartale ", ewaluowana_edycja," r. - absolwenci ", dopelniacz(typ_szk)," z ", ewaluowany_rok_abs, " r. - w podziale na zawody o największej liczbie absolwentów\n\n")
  
dane_tab_W1(pelna_finalna_ramka_wskaznikow, 
            typ_szk, "nazwa_zaw", ewaluowany_rok_abs, 
            ewaluowana_edycja, tylko_tabele) %>%
  gentab_tab_D(ewaluowana_edycja)
}
```
